### ISSUE TITLE
Add snippets to Vue

### ISSUE THREAD

**Issue by chetanraj** [chetanraj/snpt#1]

**Comment by rajkharvar** [comment]
I would like to work on it.

**Comment by rajkharvar** [comment]
I would like to add `default-vue`. Please suggest some other snippets to add other than this.

**Comment by chetanraj** [comment]
Let me curate a list..

**Comment by chetanraj** [comment]
@rajkharvar - Actually there a lot of API methods in Vue, v-if v-else to start with.. the most used ones..

**Comment by rajkharvar** [comment]
v-if, v-else they all are directives. It would be much better if we start with boilerplate and then adding all the directives. Please let me know if you like the suggestion else I can work on the same.

**Comment by chetanraj** [comment]
no issues, please add
