### ISSUE TITLE
Show - Snpt copied to clipboard 🎉in a notification

### ISSUE THREAD

**Issue by chetanraj** [chetanraj/snpt#13]
When we click on any button on the left, Showing a text "Snpt copied to clipboard 🎉
" currently on the bottom of the screen.

Need to change that to a notification

**Comment by PragunSaini** [comment]
Can I work on this?

**Comment by PragunSaini** [comment]
Where on the page should I display the notification?

**Comment by chetanraj** [comment]
> Where on the page should I display the notification?

Top right..
