### ISSUE TITLE
Add snippets to Vue [directives]

### ISSUE THREAD

**Issue by chetanraj** [chetanraj/snpt#14]
- v-text
- v-html
- v-show
- v-if
- v-else
- v-else-if
- v-for
- v-on
- v-bind
- v-model
- v-slot
- v-pre
- v-cloak
- v-once

**Comment by evelew** [comment]
I'll help with this!

**Comment by chetanraj** [comment]
> I'll help with this!

Please add the directives as stated in the description above..
