### ISSUE TITLE
redux - Needs review

### ISSUE THREAD

**Issue by chetanraj** [chetanraj/snpt#23]
Need to review the snippets in Redux and put them in correct category.

**Comment by KrisLamote** [comment]
Hi Chetan - can you be a little more specific?
I have a first glance at the current snpts, here's my initial thoughts:

- definately need snpts for mapStateToProps & mapDispatchToProps
- simpleContainer doesn't appeal to me, maybe rather a vontainer that just uses mapStateToProps and another that defined and uses both state & dispatch

Shall I make a suggestion for those?

Then in reducers I use following pattern all the time:

```javascript
const { attrib1, attrib2 } = action;

return Object.assign({}, state, {
    attrib1,
    attrib2
});
```

Don't know whether that can be useful - maybe personal flavour.. just my 2 cents

Cheers - nice project,
Kris

**Comment by chetanraj** [comment]
Hey @KrisLamote, thanks for showing interest in this issue.

What I needed was to review the current redux snippets and if anything is missing, to add them.

Yes you can add mapStateToProps & mapDispatchToProps
