### ISSUE TITLE
To fix unique "key" prop issue

### ISSUE THREAD

**Issue by chetanraj** [chetanraj/snpt#25]
To Fix
----
index.js:1375 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Snippets`. See https://fb.me/react-warning-keys for more information.
    in Fragment (created by Snippets)
    in Snippets (at App.js:63)
    in div (at App.js:46)
    in div (at App.js:45)
    in div (at App.js:43)
    in App (at src/index.js:6)

**Comment by brainfart-be** [comment]
I'm trying to fix this one ;)

**Comment by NeonNature** [comment]
May I take this issue please?

**Comment by brainfart-be** [comment]
oh i didn't saw your message '-__- really sorry

**Comment by chetanraj** [comment]
@brainfart-be still the issue persists

**Comment by brainfart-be** [comment]
@chetanraj Should i download the React DevTool to see that? my console is empty

**Comment by chetanraj** [comment]
yup, just check once

**Comment by brainfart-be** [comment]
![Screenshot 2019-10-02 at 21 13 30](https://user-images.githubusercontent.com/48967967/66075355-b8fec600-e55b-11e9-9daa-6257d84458d3.png)
Could you send me a printscreen or some kind of clue ? 
I still see no error on my side

**Comment by chetanraj** [comment]
<img width="1440" alt="Screenshot 2019-10-03 at 1 01 17 AM" src="https://user-images.githubusercontent.com/1386629/66075483-574d5480-e579-11e9-86ff-aa16fabfbb0d.png">

here you go

**Comment by brainfart-be** [comment]
Thank you, i will clone again the repo to make sure ;)

**Comment by enka** [comment]
I have a solution for this, will send a PR with the fix.

**Comment by gabrieltrompiz** [comment]
Just fixed it and made a pull request.
