### ISSUE TITLE
Add option to React Native

### ISSUE THREAD

**Issue by andrewdazs** [chetanraj/snpt#33]
It would be interesting to have an option for React Native snippets and I would be happy to add, what do you think?

**Comment by chetanraj** [comment]
Thanks, It's an good idea. But for adding one or more, the place on left tabs will not be sufficient. Let me think of an design for that. 

For now you can add React Native snippets

**Comment by andrewdazs** [comment]
Ow thank you, I'll start to add some RN snippets today :)
